### ISSUE TITLE
Status bar icon issue

### ISSUE THREAD

**Issue by d-shaktiranjan** [kattya9512/device_xiaomi_redwood#5]
## Bug description
- When networks changes then whole status bar icons re-appears.
- And some times some uneven spaces between status bar icons.  For this I collect a screenshot from a telegram user.

## Logs
[statusbar_icon.txt](https://github.com/kartik-commits/device_xiaomi_redwood/files/14909923/statusbar_icon.txt)

## Screenshots
![statusbar_icon_spaces](https://github.com/kartik-commits/device_xiaomi_redwood/assets/51184377/03e46b2c-6ff3-41c0-a30c-766c7ebf4af1)

**Comment by kartik-commits** [comment]
It is what it is in AOSP source
